name: Terraform CI

on:
  push:
    branches:
      - main
      - feature/ankush
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Terraform Init
      - name: Terraform Init
        working-directory: ./parent_modules
        run: terraform init

      # 4. Terraform Format Check
      - name: Terraform Format Check
        working-directory: ./parent_modules
        run: terraform fmt -check

      # 5. Terraform Validate
      - name: Terraform Validate
        working-directory: ./parent_modules
        run: terraform validate

      # 6. Setup TFLint
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5

      # 7. Run TFLint
      - name: Run TFLint
        working-directory: ./parent_modules
        run: |
          tflint --init
          tflint

      # 8. Install tfsec
      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      # 9. Run tfsec Security Scan
      - name: Run tfsec
        run: tfsec .

      # 10. Run Gitleaks Secret Scan
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 11. Setup Infracost
      - name: Setup Infracost
        uses: infracost/actions/setup@v3

      # 12. Run Infracost
      - name: Run Infracost
        working-directory: ./parent_modules
        run: |
          infracost breakdown \
            --path . \
            --format json \
            --out-file infracost.json
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
